server:
  port: 9821

spring:
  application:
    name: cground-payment-app
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://125.180.87.49:2206/cground_payment
    username: cground_payment
    password: cground_payment12!@
  profiles:
    active: local
    group:
      local:
        - console-logging
      test:
        - console-logging
        - file-logging
      prod:
        - console-logging
        - file-logging
  thymeleaf:
    cache: false

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    open-in-view: false
    show-sql: false
